apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-1111-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 72m
        memory: 256M
      requests:
        cpu: 18m
        memory: 128M
