apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-0001-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: 128M