apiVersion: v1
kind: Pod
metadata:
  name: ocf-pod-0101-burstable
  namespace: ocf-limits-workshop
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: 256M
      requests:
        memory: 128M
