---
apiVersion: v1
kind: LimitRange
metadata:
  name: ocf-limitrange
spec:
  limits:
  - default:                  
      cpu: 18m                
      memory: 128M            
    defaultRequest:
      cpu: 18m                
      memory: 128M
    max:
      cpu: 72m
      memory: 2G
    maxLimitRequestRatio:
      cpu: 1
      memory: 1
    min:
      cpu: 18m
      memory: 128M
    type: Container
  - max:                      
      cpu: 72m
      memory: 2G
    maxLimitRequestRatio:
      cpu: 1
      memory: 1
    min:
      cpu: 18m
      memory: 128M
    type: Pod
---
